### ISSUE TITLE
Inconsistent Tile Geometries

### ISSUE THREAD

**Issue by yellowcap** [sinergise/sentinelhub#3]
I wanted to report an inconsistency on the tile geometry of two images that belong to the same MGRS grid cell. The tile geometry is not the same in the two links below:

http://sentinel-s2-l1c.s3.amazonaws.com/tiles/22/J/BP/2015/11/28/0/tileInfo.json

http://sentinel-s2-l1c.s3.amazonaws.com/tiles/22/J/BP/2017/3/29/0/tileInfo.json

It looks like the 2015 tile geometry is set to a wrong MGRS tile.

**Comment by gmilcinski** [comment]
Hi there,
you should not assume that MGRS tiles are the same throughout the time. In the first few months ESA was changing a "default MGRS tiles" file quite a few times. The "MGRS version" is stated somewhere in the product meta-data and you can even google these older versions somewhere on the ESA web-site. 
Due to this fact we have actually established "tile geometry" information in the JSON.
So, in this came, tile geometry is almost certainly correct.
Best, Grega

**Comment by yellowcap** [comment]
Good to know, I was not aware of that, thanks for the info! Do you write the MGRS version in the json metadata you produce? I could not find it in the metadata files on S3.

**Comment by gmilcinski** [comment]
No, this is not in json metadata. It is in one of the Sentinel-2 core meta-data files. I do not know at this moment, where exactly, but I am certain you can find it in the document describing the S-2 product.
